name: demo
recipe: drupal9
config:
  webroot: ./web
  php: '8.1'
tooling:
  composer:
    service: appserver
    cmd: /usr/local/bin/composer
  drush:
    cmd:
      - /app/vendor/bin/drush --root=/app/web